# Generated by Django 6.0.6 on 2026-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Cloudinary public_id — filled automatically when you upload via admin', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used if no Cloudinary image)'),
        ),
    ]
