# Generated by Django 6.0.7 on 2026-07-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_newsletter_newspost_productreview'),
        ('core', '0002_product_image_alter_product_image_url'),
    ]

    operations = [
    ]
